### ISSUE TITLE
LoadError: cannot load such file -- dotenv/load

### ISSUE THREAD

**Issue by D1360-64RC14** [FernandoMorais/kubernetes-the-morais-way#1]
![image](https://user-images.githubusercontent.com/33406930/86877455-4d82ef80-c0bd-11ea-9a7c-7e6e825ce2a6.png)

**Sistema Operacional:** Manjaro Linux
**Virtual Box Version:** 6.1.10-1
**Vagrant Version:** 2.2.9-2
**Ansible Version:** 2.9.10-1
**Python Version:** 3.8.3

**Comment by D1360-64RC14** [comment]
Vou tentar instalar a versão 2.8 do Ansible

Edit: `Mesmo erro`

**Comment by D1360-64RC14** [comment]
Mesmo erro

**Comment by FernandoMorais** [comment]
@D1360-64RC14 

Executa esse comando aqui e envia o retorno!
`vagrant plugin list | grep dotenv`

**Comment by D1360-64RC14** [comment]
```
> vagrant plugin list
vagrant-env (0.0.3, global)
```

**Comment by FernandoMorais** [comment]
@D1360-64RC14 

O plugin certo é este aqui:
`vagrant plugin install dotenv --plugin-version 2.7.5`
