### ISSUE TITLE
Problemas com unicode no ingress values

### ISSUE THREAD

**Issue by fernandocchaves** [FernandoMorais/kubernetes-the-morais-way#12]
Ao rodar o cluster tive problemas com o externalIP do ingress, ele esta recebendo os valores como unicode no array, como esta salvando no formato incorreto ele não sobe corretamente o traefik.

**Comment by fernandocchaves** [comment]
PR com a correção: https://github.com/FernandoMorais/kubernetes-the-morais-way/pull/11

**Comment by FernandoMorais** [comment]
Valeu demais @fernandocchaves !
PR integrado!
