### ISSUE TITLE
Erro ao recriar as VM's com a tag do vagrant

### ISSUE THREAD

**Issue by fernandocchaves** [FernandoMorais/kubernetes-the-morais-way#4]
Estou tendo problemas ao recriar as VM's com a tag do vagrant, se eu comento elas elas funcionam perfeitamente porem da o erro "`error: error upgrading connection: error dialing backend: dial tcp: lookup k8s-worker-2 on 10.0.2.3:53: server misbehaving`", ja tentei criar as VM's com a tag comentada e depois rodar o provision com a tag mas este erro permanece.

Quando tento recriar as VM's do zero com a tag tenho o seguinte erro:
`TASK [dns-addon : Deploy the coredns cluster add-on] ***************************`
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.17.177.40', port=6443): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdccb7495f8>: Failed to establish a new connection: [Errno 111] Connection refused',))
fatal: [k8s-controller]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connection.py\", line 160, in _new_conn\r\n    (self._dns_host, self.port), self.timeout, **extra_kw\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/util/connection.py\", line 84, in create_connection\r\n    raise err\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/util/connection.py\", line 74, in create_connection\r\n    sock.connect(sa)\r\nConnectionRefusedError: [Errno 111] Connection refused\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 677, in urlopen\r\n    chunked=chunked,\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 381, in _make_request\r\n    self._validate_conn(conn)\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 978, in _validate_conn\r\n    conn.connect()\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connection.py\", line 309, in connect\r\n    conn = self._new_conn()\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connection.py\", line 172, in _new_conn\r\n    self, \"Failed to establish a new connection: %s\" % e\r\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdccb7495f8>: Failed to establish a new connection: [Errno 111] Connection refused\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1597366096.59-14305-165333972825582/AnsiballZ_k8s.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1597366096.59-14305-165333972825582/AnsiballZ_k8s.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1597366096.59-14305-165333972825582/AnsiballZ_k8s.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.clustering.k8s.k8s', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_k8s_payload_8y6xjlfh/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 281, in <module>\r\n  File \"/tmp/ansible_k8s_payload_8y6xjlfh/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 277, in main\r\n  File \"/tmp/ansible_k8s_payload_8y6xjlfh/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 171, in execute_module\r\n  File \"/tmp/ansible_k8s_payload_8y6xjlfh/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py\", line 200, in get_api_client\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/client.py\", line 71, in __init__\r\n    self.__discoverer = discoverer(self, cache_file)\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/discovery.py\", line 259, in __init__\r\n    Discoverer.__init__(self, client, cache_file)\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/discovery.py\", line 31, in __init__\r\n    self.__init_cache()\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/discovery.py\", line 78, in __init_cache\r\n    self._load_server_info()\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/discovery.py\", line 158, in _load_server_info\r\n    'kubernetes': self.client.request('get', '/version', serializer=just_json)\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/client.py\", line 42, in inner\r\n    resp = func(self, *args, **kwargs)\r\n  File \"/root/.local/lib/python3.6/site-packages/openshift/dynamic/client.py\", line 247, in request\r\n    _return_http_data_only=params.get('_return_http_data_only', True)\r\n  File \"/root/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py\", line 345, in call_api\r\n    _preload_content, _request_timeout)\r\n  File \"/root/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py\", line 176, in __call_api\r\n    _request_timeout=_request_timeout)\r\n  File \"/root/.local/lib/python3.6/site-packages/kubernetes/client/api_client.py\", line 366, in request\r\n    headers=headers)\r\n  File \"/root/.local/lib/python3.6/site-packages/kubernetes/client/rest.py\", line 241, in GET\r\n    query_params=query_params)\r\n  File \"/root/.local/lib/python3.6/site-packages/kubernetes/client/rest.py\", line 214, in request\r\n    headers=headers)\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/request.py\", line 76, in request\r\n    method, url, fields=fields, headers=headers, **urlopen_kw\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/request.py\", line 97, in request_encode_url\r\n    return self.urlopen(method, url, **extra_kw)\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/poolmanager.py\", line 336, in urlopen\r\n    response = conn.urlopen(method, u.request_uri, **kw)\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 767, in urlopen\r\n    **response_kw\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 767, in urlopen\r\n    **response_kw\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 767, in urlopen\r\n    **response_kw\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 727, in urlopen\r\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\r\n  File \"/root/.local/lib/python3.6/site-packages/urllib3/util/retry.py\", line 439, in increment\r\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\r\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.17.177.40', port=6443): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdccb7495f8>: Failed to establish a new connection: [Errno 111] Connection refused',))\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

Mudei a faixa de IP do 192 para 172 apenas porque achei que poderia ser algum problema com a rede do virtualbox.

Estou usando as seguintes versões:
Vagrant: 2.2.9
Ansible: 2.9.11
VirtualBox: 6.0.14_Ubuntu r132055
Ubuntu: 19.10

**Comment by FernandoMorais** [comment]
Fernando, encontrei a causa do erro e vou ajustar na live de hoje.

Ele ocorre por estarmos tentando instalar o add-on com o cluster ainda em estado not ready!

Descobri que o problema está ligado à definição de tags também!
